services:
  database:
    image: mysql:8.1
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PWD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${USER_NAME}
      MYSQL_PASSWORD: ${USER_PWD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - webnet

  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      APP_ENV: local
      APP_DEBUG: true
      DB_CONNECTION: mysql
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: ${DB_NAME}
      DB_USERNAME: ${USER_NAME}
      DB_PASSWORD: ${USER_PWD}
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor
    ports:
      - "${PORT_API}:80"
    networks:
      - webnet
    depends_on:
      - database
    entrypoint: ["/var/www/html/entrypoint.sh"]

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "${PORT_CLIENT}:80"
    networks:
      - webnet
    depends_on:
      - backend

volumes:
  db_data:

networks:
  webnet:
