services:
  
  database:
    image: mysql:8.1
    container_name: todo-db
    ports:
      - "3306:3306"
    networks:
      - webnet
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PWD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${USER_NAME}
      MYSQL_PASSWORD: ${USER_PWD}
    volumes:
      - db_data:/var/lib/mysql

  backend:
    image: php:8.3-apache
    container_name: todo-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
      - PHP_OPCACHE_ENABLE=1
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1
    ports:
      - "8000:80"
    networks:
      - webnet
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: nginx:latest  # Usando a imagem oficial do NGINX
    container_name: todo-frontend
    ports:
      - "8080:80"
    networks:
      - webnet
    depends_on:
      - backend

volumes:
  db_data:

networks:
  webnet: